version: '3.1'
services:

  mqtt:
    image: eclipse-mosquitto
    env_file:
      - .env
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
      - "9001:9001"

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - mqtt

  client:
    build: ./client
    command: python client.py
    env_file:
      - .env
    volumes:
      - ./client:/code
      - /dev:/dev
    depends_on:
      - mqtt