version: '3.1'
services:

  mqtt:
    image: eclipse-mosquitto
    env_file:
      - .env
    ports:
      - "1883:1883"

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./:/code
    ports:
      - "8000:8000"

  client:
    build: ./client
    command: python run.py
    env_file:
      - .env
    volumes:
      - ./client:/code

