version: '3.1'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build: ./
    command: python /code/run.py
    env_file:
      - .env
    volumes:
      - ./client:/code
    depends_on:
      - db

  mqtt:
    image: eclipse-mosquitto
    env_file:
      - .env
    ports:
      - "1883:1883"