version: '3.1'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  mqtt:
    image: rabbitmq
    env_file:
      - .env
    ports:
      - "1883:1883"